---
- name: Disable selinux
  selinux:
    state: disabled

- name: Be sure firewalld is stopped
  systemd:
    name: firewalld
    enabled: no
    state: stopped
  ignore_errors: yes

- name: Install epel-repo
  yum:
    name: epel-release
    state: present

- name: Install remi-repo
  yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - gcc-c++
    - make
    - automake
    - wget
    - telnet
    - yum-utils
    - git
    - python-devel

- name: Enable remi php
  command: yum-config-manager --enable "remi-{{ php_version }}"

- name: check to see if pip is already installed
  command: "pip --version"
  ignore_errors: true
  register: pip_is_installed
  changed_when: false

- block:

  - name: download get-pip.py
    get_url: url=https://bootstrap.pypa.io/get-pip.py  dest=/tmp

  - name: install pip
    command: "python /tmp/get-pip.py"

  - name: delete get-pip.py
    file: state=absent path=/tmp/get-pip.py
  when: pip_is_installed.rc != 0
